### PR TITLE
Simplify the plugin related build tasks

### LINKED ISSUE #1104: Fix grunt watch for plugins
There are a couple of problems with the grunt watch task particularly applied to plugin development.

1. The plugin specific tasks aren't initialized until the `plugin` task is run (see [here](https://github.com/girder/girder/blob/master/grunt_tasks/plugin.js#L212)).  For the moment, we can work around this by running `grunt plugin watch` instead, but that block of code should be moved to the previous loop where the plugins are detected.

2.  It appears as if some of the globs in the subtask definitions are picking up wrong and/or extra paths.  See https://github.com/Kitware/minerva/issues/208.

### PR DESCRIPTION
**Pull request by jbeezley**
This removes the grunt templates that were previously used to generate "generic" configurations for plugin tasks.  There are several benefits for this change:

  * you can now run task categories like `grunt uglify`
  * plugins can more easily change their own configuration
  * less black magic

Fixes #1104.  I tested it with minerva and there were no issues.  `grunt watch` works for files under `web_client`, and I verified that `touch plugins/minerva/web_client/templates/minerva_config.jade` run both the jade and uglify tasks.  I'm really trying to not break plugins this time, I promise.

For #1114.  With this change, there is no magic there so it should be possible to just append to the sources to the grunt config object if we want to make that part of the API surface.  Otherwise, this should make implementing the suggestion in #1114 straightforward.

For testing, the packaging tests do a descent job of covering this code except for the `watch` tasks.  I'm up for suggestions if and how that should be done.

### CODE REVIEW

File: grunt_tasks/plugin.js [hunk 1]
```diff
@@ -24,98 +24,140 @@ module.exports = function (grunt) {
...
-                    execOptions: {
-                        cwd: path.resolve(process.cwd(), 'plugins')
-                    }
-                },
-                src: ['<%= grunt.config.get("pluginDir") %>/<%= grunt.task.current.args[0] %>/package.json']
-            }
-        },
-        'plugin-install': {}
-    });
+    var configure_plugin = function (plugin) {
```
Comment (zachmullen) [inline grunt_tasks/plugin.js]: Let's use camel case rather than underscore

Comment (jbeezley) [inline grunt_tasks/plugin.js]: Done

**Comment by zachmullen** [comment]
@jbeezley this fixed the issue with `grunt watch` for plugin template changes, but it's still not working for core template changes (maybe we want to put that off to another issue).

Do we now have some "official" (non hacky) way of allowing plugins to add their own JS and CSS files into their built files?

**Comment by jbeezley** [comment]
I was targeting plugin issues here, but if you want me to address the core watch task as well, I don't think it should be too hard.

As for #1114, I was postponing a true fix for a later PR as we should discuss what we need in terms flexibility for the plugin build steps.  I don't necessarily consider monkey patching the `config.uglify.myPlugin.files` array as overly hacky.  This PR at the very least makes that possible again.

**Comment by zachmullen** [comment]
>  I don't necessarily consider monkey patching the config.uglify.myPlugin.files array as overly hacky.

The syntax for doing it was pretty ugly since you have to explicitly read the value, change it, then write it back, and obviously I was not considering those things part of the API surface, just a quick and dirty hack that worked. I'm glad this at least restores that capability, but I'd like to go ahead and implement #1114 to make this easier on plugin devs with npm or bower deps. If you don't have time, let me know and I will go ahead and implement it.

This branch LGTM. @girder/developers do we think all of our grunt config names and behaviors should be part of the API surface? We should adopt a policy on this sooner rather than later.

**Comment by jbeezley** [comment]
For the record, I wasn't advocating monkey patching, but it would expose the most power to the plugins.  I'm more in favor of a declarative approach.  For example, a list of files in `plugin.json`:

```javascript
{
  uglify: [...],
  jade: [...],
  stylus: [...]
}
```

I probably won't be able to implement any of this in the next week or so.  If you want it, feel free.

**Comment by zachmullen** [comment]
I like that, maybe something like:

```
grunt:
    uglify:
        prepend: [file1, file2]
        append: [file1, file2]
        override: [<full list of files, will override default values>]
```

**Comment by zachmullen** [comment]
And I might change "uglify" and "stylus" to "js" and "css" so that the declaration is technology-independent as well.

**Comment by jbeezley** [comment]
This may be unrelated, but should there be a mechanism for plugins to bundle code for the `test-env-html` task? Is there a better way to do what [Minerva does](https://github.com/Kitware/minerva/blob/master/Gruntfile.js#L252)?

**Comment by zachmullen** [comment]
I don't think a better way exists at this time, but it would be nice to add a utility function that could be used to aggregate the necessary sources.

**Comment by jbeezley** [comment]
@zachmullen I threw in a fix for the `watch:js_core` task as well.

**Comment by zachmullen** [comment]
Thanks, LGTM

**Comment by mgrauer** [comment]
@jbeezley This was a nice improvement.

@zachmullen 

> do we think all of our grunt config names and behaviors should be part of the API surface?

on behalf of Minerva, yes.
